import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      // app/layout.tsx  (inside the <body>)
      <body className="min-h-screen bg-gray-50 font-sans">
        <header className="border-b bg-white">
          <div className="max-w-6xl mx-auto p-4 flex justify-between">
            <span className="font-bold">🛡 Guardrail AI</span>
            {/* TODO: user avatar / plan info */}
          </div>
        </header>

        <main className="max-w-6xl mx-auto p-6">
          {children}
        </main>
      </body>

    </html>
  );
}
